# Generated by Django 4.2.1 on 2023-06-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customeraddresss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddresss',
            name='landmark',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customeraddresss',
            name='pincode',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customeraddresss',
            name='taluka',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customeraddresss',
            name='village_city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customeraddresss',
            name='ward',
            field=models.TextField(null=True),
        ),
    ]
