# Generated by Django 4.2.1 on 2023-06-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customeraddresss_landmark_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerAddresss',
            new_name='CustomerAddress',
        ),
    ]
