# Generated by Django 4.2.1 on 2023-06-07 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_food_category_foodcategory'),
        ('cart', '0002_alter_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='name',
        ),
        migrations.RemoveField(
            model_name='items',
            name='price',
        ),
        migrations.AddField(
            model_name='items',
            name='food_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.food'),
            preserve_default=False,
        ),
    ]
