# Generated by Django 4.2.1 on 2023-06-05 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('plate_pieces', models.CharField(max_length=50)),
                ('item_img', models.ImageField(default='default_food.png', upload_to='item_imgs')),
                ('food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food_category')),
            ],
        ),
    ]
