# Generated by Django 4.2.1 on 2023-06-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_food_item_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='food_category',
            new_name='FoodCategory',
        ),
    ]
